# Generated by Django 5.1.10 on 2026-07-06 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('delimiter', models.CharField(default=';', max_length=1)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('isrc', models.CharField(blank=True, max_length=12)),
                ('search_query', models.CharField(max_length=600)),
                ('status', models.CharField(choices=[('pending', 'Pendente')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='downloads.trackimport')),
            ],
            options={
                'ordering': ['row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('track_import', 'row_number'), name='unique_import_row_number')],
            },
        ),
    ]
