# Generated by Django 5.1.10 on 2026-07-06 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_trackimportitem_download_progress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackImportItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('remote_filename', models.CharField(max_length=1000)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('bit_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('queue_length', models.PositiveIntegerField(default=0)),
                ('upload_speed', models.BigIntegerField(default=0)),
                ('download_requested_at', models.DateTimeField(blank=True, null=True)),
                ('download_state', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='downloads.trackimportitem')),
            ],
            options={
                'ordering': ['item', 'rank', '-score'],
                'constraints': [models.UniqueConstraint(fields=('item', 'username', 'remote_filename', 'size_bytes'), name='unique_import_item_source')],
            },
        ),
    ]
