# Generated by Django 5.1.10 on 2026-07-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_trackimportitemsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackimportitem',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackimportitem',
            name='search_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackimportitem',
            name='search_response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackimportitem',
            name='search_slskd_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='trackimportitem',
            name='search_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackimportitem',
            name='search_state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
