# Generated by Django 5.1.10 on 2026-07-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_trackimportitem_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackimportitem',
            name='search_query_mode',
            field=models.CharField(choices=[('auto', 'Automatica'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
    ]
