# Generated by Django 5.1.10 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0005_trackimportitem_search_query_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackimport",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackimport",
            name="processing_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackimport",
            name="processing_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trackimport",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackimport",
            name="processing_task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
