# Generated by Django 5.1.10 on 2026-07-06 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'monitored directories',
                'ordering': ['name', 'path'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=128)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('bitrate_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='library.track')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_files', to='mediafiles.monitoreddirectory')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
