# Generated by Django 5.1.10 on 2026-07-06 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='duplicate_confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='mediafiles.mediafile'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='duplicate_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
