# Generated by Django 5.1.10 on 2026-07-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_track_acoustic_fingerprint_and_more'),
        ('mediafiles', '0002_mediafile_duplicate_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='import_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('duplicate', 'Duplicate'), ('review', 'Review'), ('error', 'Error')], default='imported', max_length=20),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='source_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='storage_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.UniqueConstraint(condition=models.Q(('storage_path', ''), _negated=True), fields=('storage_path',), name='unique_media_file_storage_path'),
        ),
    ]
