# Generated by Django 5.1.10 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0003_mediafile_import_status_mediafile_source_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="acoustic_fingerprint",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="acoustic_fingerprint_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
