# Generated by Django 5.1.10 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0004_mediafile_acoustic_fingerprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="original_backed_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="original_backup_path",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="original_backup_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="original_backup_status",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
