# Generated by Django 5.1.10 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0005_mediafile_original_backup_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="audio_format",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="is_master",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="origin_type",
            field=models.CharField(
                choices=[("original", "Original"), ("derived", "Derived")],
                default="original",
                max_length=20,
            ),
        ),
    ]
