# Generated by Django 5.1.10 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0006_mediafile_audio_format_mediafile_origin_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("backend_type", models.CharField(choices=[("s3", "S3"), ("sftp", "SFTP")], max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("base_path", models.TextField(blank=True)),
                ("aws_bucket", models.CharField(blank=True, max_length=120)),
                ("aws_region", models.CharField(blank=True, max_length=60)),
                ("aws_access_key_id", models.CharField(blank=True, max_length=120)),
                ("aws_secret_access_key", models.CharField(blank=True, max_length=255)),
                ("aws_endpoint_url", models.TextField(blank=True)),
                ("aws_prefix", models.TextField(blank=True)),
                ("sftp_host", models.CharField(blank=True, max_length=255)),
                ("sftp_port", models.PositiveIntegerField(blank=True, null=True)),
                ("sftp_username", models.CharField(blank=True, max_length=120)),
                ("sftp_password", models.CharField(blank=True, max_length=255)),
                ("sftp_private_key", models.TextField(blank=True)),
                ("sftp_remote_path", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
    ]
