# Generated by Django 5.1.10 on 2026-07-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0007_backuptarget"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="backup_target",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="media_files", to="mediafiles.backuptarget"),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="original_backup_status",
            field=models.CharField(blank=True, choices=[("pending", "Pending"), ("uploaded", "Uploaded"), ("confirmed", "Confirmed"), ("failed", "Failed")], max_length=20),
        ),
    ]
