# Generated by Django 5.1.10 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0008_mediafile_backup_target_and_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="transcode_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="transcode_status",
            field=models.CharField(blank=True, choices=[("pending", "Pending"), ("processing", "Processing"), ("completed", "Completed"), ("failed", "Failed")], max_length=20),
        ),
    ]
