# Generated by Django 5.1.10 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediafiles", "0009_mediafile_transcode_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="local_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
